// DepartmentConstants.js
export const DEPARTMENTS = {
  ALL_TEAMS: 'All teams',
  ANALYTICS: 'Analytics',
  DONATIONS: 'Donations',
  ENGINEERING: 'Engineering',
  POLITICAL_DATA: 'Political Data',
  OTHER: 'Other',
};

export const DEPARTMENT_LIST = [
  DEPARTMENTS.ALL_TEAMS,
  DEPARTMENTS.ANALYTICS,
  DEPARTMENTS.DONATIONS,
  DEPARTMENTS.ENGINEERING,
  DEPARTMENTS.POLITICAL_DATA,
  DEPARTMENTS.OTHER,
];

export default DEPARTMENTS;
